[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100000000000000
# Secret key: 753b7cc01a1a2e86221266a154af739463fce51219d97e4f856cd7200c3bd2a601
# Public key: 0390a5cac7c33fda49f70bc1b0866fa0ba7a9440d9de647fecb8132ceb76a94ddd
# Address: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100000000000000
# Secret key: 7287ba251d44a4d3fd9276c88ce34c5c52a038955511cccaf77e61068649c17801
# Public key: 03d8015134d9db8178ac93acbc43170a2f20febba5087a5b0437058765ad5133d0
# Address: ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100000000000000
# Secret key: 530d9f61984c888536871c6573073bdfc0058896dc1adfe9a6a10dfacadc209101
# Public key: 02ead0b33d8a00b4b3c9d9e2d6b5b6b5b6b5b6b5b6b5b6b5b6b5b6b5b6b5b6b5
# Address: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom prime crater oppose divert carrot jaw era wire debate current moral turn sentence invest"
balance = 100000000000000
# Secret key: d655b2523bcd65e34889725c73064feb17ceb796831c0e111ba1a552b0f31b3901
# Public key: 03ad618df73b297b9b9f2d0e7a7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b
# Address: ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC

[accounts.wallet_4]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100000000000000
# Secret key: f9d7206a47f14d2870c163ebab4bf3e70d18f5d14ce1031f3902fbbc894fe4c701
# Public key: 03a2f0681a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a3a
# Address: ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND
